/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 사용자 로그인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example mypassword123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 로그인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 로그인에 성공했습니다. */
                            message?: string;
                            data?: {
                                /**
                                 * @description JWT 토큰
                                 * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                                 */
                                token?: string;
                                user?: {
                                    /** @example 608c1f9b4f1a4629a4e9c8a1 */
                                    id?: string;
                                    /** @example user@example.com */
                                    email?: string;
                                    /** @example user */
                                    role?: string;
                                };
                            };
                        };
                    };
                };
                /** @description 요청 데이터 유효성 검사 실패 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 이메일 형식이 올바르지 않습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 존재하지 않는 회원이거나 비밀번호 불일치 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 잘못된 비밀번호입니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example mypassword123 */
                        password: string;
                        /** @example cooluser */
                        nickname: string;
                    };
                };
            };
            responses: {
                /** @description 회원가입 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 회원가입 성공! */
                            message?: string;
                            data?: {
                                user?: {
                                    /** @example 608c1f9b4f1a4629a4e9c8a1 */
                                    _id?: string;
                                    /** @example user@example.com */
                                    email?: string;
                                    /** @example cooluser */
                                    nickname?: string;
                                };
                            };
                        };
                    };
                };
                /** @description 요청 데이터 유효성 검사 실패 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 이메일 형식이 올바르지 않습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 이미 존재하는 이메일 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 이미 존재하는 이메일입니다. */
                            message?: string;
                            user?: null;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 로그인한 사용자 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 사용자 정보 반환 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example  */
                            message?: string;
                            data?: {
                                user?: {
                                    /** @example 608c1f9b4f1a4629a4e9c8a1 */
                                    id?: string;
                                    /** @example user@example.com */
                                    email?: string;
                                    /** @example cooluser */
                                    nickname?: string;
                                    /** @example user */
                                    role?: string;
                                };
                            };
                        };
                    };
                };
                /** @description 인증 실패 (토큰 없음 또는 만료) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 인증이 필요합니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 존재하지 않는 회원 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 존재하지 않는 회원입니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증 코드 전송 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description 이메일 전송 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 이메일 전송에 성공했습니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 30초 이내 재전송 제한 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 이전 전송 30초 이후 재전송 가능합니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check-verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증 코드 확인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example 123456 */
                        code: number;
                    };
                };
            };
            responses: {
                /** @description 인증 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 인증에 성공했습니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 인증 실패 (코드 불일치) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 인증에 실패했습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/check-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 가입 가능 여부 확인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description 가입 가능한 이메일일 경우 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 가입 가능한 이메일입니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 이미 존재하는 이메일일 경우 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 가입이 불가능한 이메일입니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 비밀번호 변경 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /** @example newStrongPassword123 */
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description 비밀번호 변경 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 비밀번호가 성공적으로 변경되었습니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 해당 이메일 유저 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 해당 이메일의 유저를 찾을 수 없습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 모든 맵 리스트 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 맵 리스트 반환 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 성공적으로 맵 리스트를 가져왔습니다. */
                            message?: string;
                            data?: {
                                /** @example 645f3d8f2345abcd12345680 */
                                _id: string;
                                /** @example office */
                                name: string;
                                /** @example https://pub-b1bcdfea0c06423d871965b53c9a3103.r2.dev/thumbnails/office.png */
                                thumbnail: string;
                                /** @example https://pub-b1bcdfea0c06423d871965b53c9a3103.r2.dev/thumbnails/office.json */
                                source: string;
                            }[];
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 새 맵 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Sample Map */
                        name: string;
                        /** @example https://example.com/image.jpg */
                        thumbnail: string;
                        /** @example https://example.com/map-source */
                        source: string;
                    };
                };
            };
            responses: {
                /** @description 맵 생성 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 성공적으로 맵을 생성했습니다. */
                            message?: string;
                            data?: {
                                /** @example 645f3d8f2345abcd12345678 */
                                _id?: string;
                                /** @example Sample Map */
                                name?: string;
                                /** @example https://example.com/image.jpg */
                                thumbnail?: string;
                                /** @example https://example.com/map-source */
                                source?: string;
                            };
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 사용자가 참여한 방 리스트 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 참여한 방 리스트 반환 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 참여한 방 리스트입니다. */
                            message?: string;
                            data?: {
                                /**
                                 * Format: objectId
                                 * @example 645f3d8f2345abcd12340001
                                 */
                                userId?: string;
                                /**
                                 * Format: date-time
                                 * @example 2025-05-20T14:00:00Z
                                 */
                                joinedAt?: string;
                                room?: {
                                    /** @example 645f3d8f2345abcd12345679 */
                                    _id?: string;
                                    /** @example Sample Room */
                                    title?: string;
                                    /** @example abcd12345679 */
                                    host?: string;
                                    /** @example 4 */
                                    headCount?: number;
                                    /** @example 68160673c9a7b70fb5cabb8b */
                                    mapId?: string;
                                };
                                map?: {
                                    /** @example 645f3d8f2345abcd12345680 */
                                    _id?: string;
                                    /** @example office */
                                    name?: string;
                                    /** @example https://pub-b1bcdfea0c06423d871965b53c9a3103.r2.dev/thumbnails/office.png */
                                    thumbnail?: string;
                                    /** @example https://pub-b1bcdfea0c06423d871965b53c9a3103.r2.dev/thumbnails/office.json */
                                    source?: string;
                                };
                            }[];
                        };
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 방 생성 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 새로운 방 */
                        title: string;
                        /** @example 1234 */
                        password: string;
                        /** @example 6 */
                        headCount: number;
                        /** @example office */
                        mapId: string;
                    };
                };
            };
            responses: {
                /** @description 방 생성 성공 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 방이 생성되었습니다. */
                            message?: string;
                            data?: {
                                _id?: string;
                                title?: string;
                                headCount?: number;
                                host?: string;
                                mapId?: string;
                            };
                        };
                    };
                };
                /** @description 잘못된 요청 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 특정 방의 정보 조회 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 조회할 방의 ID */
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 방 정보 조회 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example abc123방 정보입니다. */
                            message?: string;
                            data?: {
                                _id?: string;
                                name?: string;
                                host?: string;
                                isHost?: boolean;
                                title?: string;
                                mapId?: string;
                                headCount?: number;
                            };
                        };
                    };
                };
                /** @description 인증 실패 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 방 삭제 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 삭제할 방의 ID */
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 방 삭제 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 방이 성공적으로 삭제되었습니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 삭제 권한 없음 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 해당 방을 삭제할 권한이 없습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 방 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 해당 방을 찾을 수 없습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 방 입장 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 입장할 방의 ID */
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 방 입장 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 방에 입장했습니다. */
                            message?: string;
                            data?: {
                                _id?: string;
                                title?: string;
                                headCount?: number;
                                host?: string;
                                mapId?: string;
                            };
                        };
                    };
                };
                /** @description 방을 찾을 수 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 방을 찾을 수 없습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 방 비밀번호 확인 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 비밀번호를 확인할 방의 ID */
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 123456 */
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description 비밀번호 확인 성공 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 비밀번호가 일치합니다. */
                            message?: string;
                            /** @example true */
                            data?: boolean;
                        };
                    };
                };
                /** @description 방 없음 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 방을 찾을 수 없습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 비밀번호 불일치 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 비밀번호가 일치하지 않습니다. */
                            message?: string;
                        };
                    };
                };
                /** @description 서버 내부 오류 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 서버 내부 오류 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
