name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build based on branch
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            pnpm run build:prod
          else
            pnpm run build:alpha
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME_PROD }} --delete
          else
            aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME_ALPHA }} --delete
          fi

      - name: Create CloudFront invalidation
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} --paths "/*"
          else
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_ALPHA }} --paths "/*"
          fi
